/* XPM */
static char *apuapu_xpm[] = {
/* columns rows colors chars-per-pixel */
"32 56 16 1 ",
"  c #2A1912",
". c #2A1912",
"X c #372C2A",
"o c #543058",
"O c #514E5B",
"+ c #89321D",
"@ c #C75E2B",
"# c #2B9829",
"$ c #19C911",
"% c #D89D36",
"& c #F4DC40",
"* c #7A28A2",
"= c #585CC6",
"- c #B630DA",
"; c #F2E6BA",
": c #96A4C5",
/* pixels */
"OOOOOOOOOOOOOOOOOoOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOO@OOOOOOOOO*OOOO",
"OOOOOOOOOOOOOOOO@@OOOOOOOOO*OOOO",
"OOOOOOOOOOOOOOOO@+@OOOoOO*--OOOO",
"OOOOOOOOOOOOOOOO+@@OOOOOO---OOoO",
"OO=oOOO%#OOOOOO@@@@%OOOO---=OOOO",
"OO=OOOOO&&@OOOO@@@@@OOO=----*OOO",
"OO==OOOO&&&#OO@@%%%@@OO-----OOoO",
"Oo====OO%&%%%O@@%&%@OO------OoOO",
"OO=-===O%%&&%#@%&%%@@**-----*OOo",
"Oo======%&&&%%@%&&%@@*-----**OoO",
"OO=-====#%&&&@@%&&&@@*-----**OOO",
"O*===:=:=%&&&%@%&&&@O-----*-oOoO",
"OO====::=%&&&%@%&&%@*------*oOOo",
"Oo====:::#&&&&@@;%%@O-----*oOoOo",
"oOO===::::%&&&%@%%%@**---**ooooo",
"OOO===:::=%&&&@+%%@@*----**ooo*o",
"##OO===::=#&&%#+@%@O*-*-**o****X",
"X$$$O===:=O%&%%++@@o**-***o**ooO",
"o####===:=O@%%%X+@+o=****o**o*Xo",
"OX####====o#@@@O.++=**-**o**ooOo",
"XO####O===OO@#XOX+o=***oo**oooOX",
"OoX####OO=OXO@OXO+O=o*oo*ooOXOXo",
"XOXOX###OOOXO@OX+X+o+oo+ooXOXoXO",
"oXXOXXO#OXO++++++@+++@+o+XOXXOoX",
"XOXXOXXX.+....+.++@@@@@@+ooXOXXO",
"oXXoXXo.++@@@+++.++@@@+++XXXoXoX",
"XoXXoXXX+++++@@@+.+++++XXXoXXoXo",
"XXXXXXXX.++@@@@@++++@@++XXXXoXXX",
"XXXXXXXX ..+@@%%@++%&&&@+XXXXoXo",
"XXXXXXXX..+@&;;&&@@&;;;%XXXXXXXX",
"XXXXXXXX. +@&;;;&%@&;;;%+XXXXXXX",
"XX.XXX.XX.+%&;;;&@@@&&&@XXXXXXXX",
"X.XX.XXX..+%%&&&%@+%%&%@.XXXXXXX",
".XX.X.X.X..@@%%%@@++++++XX.XX.XX",
"X.X.X.X.X .X%%%%@X@+++++..XX.XXX",
"..X.X...X....O@@+.@@++++.X.X.X.X",
".X....X... ....+..+@++++..X.X.XX",
"....X..........X.X+@@+++.X..X.X.",
".......... ..+...+++%+++...X.X.X",
"..... ... ....++O+X+@@@+.......X",
". ........ ...OO++O+OO++........",
"... .. .. ...XO%:%:%:%++......X.",
" . . . . . ..X:;:::;;:O.........",
". . . . .  ..X::;;;::%@+. ......",
" . . . . . ..X@%O@+@+++.........",
"            ..XXXXXO..... ......",
"            .....XX$%@..........",
"             ....XX&OX.. .......",
"                 .X%&O........+.",
"                ...#X@. ........",
"                 . +. .......+..",
"                     . .........",
"                  . . .......+..",
"                   . . .......+.",
"                   . ..........."
};
